site_name: DragonRuby
nav:
  - 'Home':
    - Main : index.md
    - About: about.md
    - Licensing: license.md
    - Commands: 11-commands.md
  - 'Getting Started': 
    - General Information: 01-high-level.md
    - Beginner: tutorials/beginner.md
    - Intermediate: tutorials/intermediate.md
    - Advanced: tutorials/advanced.md
  - 'Tutorials': 
    - Hello World: tutorials/hello-world.md
    - Publishing Your Game: tutorials/publishing.md
  - 'Outputs': 
    - Labels: 02-labels.md
    - Solids & Borders: 03-solids-and-borders.md
    - Lines: 04-lines.md
    - Sprites: 05-sprites.md
    - Sounds: 09-sound.md
  - 'Inputs': 
    - Keyboard: 06-keyboard.md
    - Mouse: 07-mouse.md
    - Controllers: 08-controllers.md
  - 'Game States': 
    - Entities & Collisions: 10-entities-and-collisions.md
  - 'Misc': 
    - Cheatsheet: 97-cheatsheet.md
    - FAQ: 98-faq.md
    - To Do: 99-todo.md

theme:
  name: 'material'

  theme:
  palette:
    primary: 'black'
    accent: 'indigo'
  logo: 'img/console-logo.png'
  favicon: 'img/favicon.ico'

markdown_extensions:
    - toc:
        permalink: "#"
    - admonition
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde