site_name: DragonRuby
nav:
  - 'Home':
    # - Home: index.md
    - About: about.md
    - Licensing: license.md
  - 'Getting Started':
    - Tutorial: 00-tutorial.md
    - General: 01-high-level.md
  - 'Outputs':
    - Labels: 02-labels.md
    - Solids & Borders: 03-solids-and-borders.md
    - Lines: 04-lines.md
    - Sprites: 05-sprites.md
    - Sounds: 09-sound.md
  - 'Inputs':
    - Keyboard: 06-keyboard.md
    - Mouse: 07-mouse.md
    - Controllers: 08-controllers.md
  - 'Game States':
    - Entities & Collisions: 10-entities-and-collisions.md
  - 'Misc':
    - FAQ: 98-faq.md
    - ToDo: 99-todo.md


theme: readthedocs